name: CI - Tests et couverture Backend + Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'card-/**'

jobs:
  backend:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: back 
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar -Dsonar.projectKey=LauraVongsy_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD -Dsonar.organization=lauravongsy -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload rapport JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-backend
          path: target/site/jacoco
  frontend:
      runs-on: macos-latest
      needs: backend
      defaults:
        run:
          working-directory: front
      steps:
        - uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'

        - name: Installer les dépendances frontend
          run: npm install

        - name: Lancer les tests frontend avec coverage
          run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

        - name: Upload rapport de coverage frontend
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report-frontend
            path: front/coverage/bobapp
