name: CI - Tests et couverture Backend + Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'card-/**'

jobs:
  backend:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build et tests Maven avec JaCoCo
        run: mvn clean verify

      - name: Upload rapport JaCoCo (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-backend
          path: target/site/jacoco

  frontend:
    runs-on: macos-latest
    needs: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances frontend
        run: npm install

      - name: Lancer les tests frontend avec coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Upload rapport de coverage frontend
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-frontend
          path: coverage/bobapp
