name: CI - Tests et couverture Backend + Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'card-/**'

jobs:
  backend:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: back 
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build et tests Maven avec JaCoCo
        working-directory: back
        run: mvn clean verify

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Upload rapport JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-backend
          path: back/target/site/jacoco
    
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=LauraVongsy_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
      
  docker-build-push-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back  
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t lauravongsy/bobapp-back:latest .

      - name: Push Docker image to Docker Hub
        run: docker push lauravongsy/bobapp-back:latest
  frontend:
      runs-on: macos-latest
      needs: backend
      defaults:
        run:
          working-directory: front
      steps:
        - uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'

        - name: Installer les dépendances frontend
          run: npm install

        - name: Lancer les tests frontend avec coverage
          run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

        - name: Upload rapport de coverage frontend
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report-frontend
            path: front/coverage/bobapp
  docker-build-push-frontend:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: front  
      steps:
        - uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build Docker image
          run: docker build -t lauravongsy/bobapp-back:latest .

        - name: Push Docker image to Docker Hub
          run: docker push lauravongsy/bobapp-back:latest